name: General Feedback
description: Share impressions, suggestions, questions, or anything else.
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Anything goes — first impressions, confusion points, things you love or hate. No format required.
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      description: Tell us what's on your mind.
    validations:
      required: true
